DECISION_MAKER_KEYWORDS = [
    # Founders / Ownership
    "founder",
    "co-founder",
    "co founder",
    "owner",
    "partner",
    "managing partner",

    # C-Level Executives
    "ceo",
    "chief executive officer",
    "cto",
    "chief technology officer",
    "cio",
    "chief information officer",
    "cfo",
    "chief financial officer",
    "coo",
    "chief operating officer",
    "cmo",
    "chief marketing officer",
    "cro",
    "chief revenue officer",
    "cpo",
    "chief product officer",
    "chro",
    "chief human resources officer",
    "ciso",
    "chief information security officer",
    "chief",
    "executive",

    # Senior Leadership
    "president",
    "vice president",
    "vp",
    "svp",
    "evp",
    "avp",
    "general manager",
    "gm",
    "country head",
    "regional head",
    "business head",

    # Directors / Heads
    "director",
    "technical director",
    "engineering director",
    "product director",
    "sales director",
    "marketing director",
    "hr director",
    "operations director",
    "head",
    "head of engineering",
    "head of product",
    "head of sales",
    "head of marketing",
    "head of hr",
    "head of technology",
    "head of operations",

    # Engineering / Tech
    "engineering manager",
    "software engineering manager",
    "development manager",
    "technical manager",
    "it manager",
    "devops manager",
    "platform manager",
    "tech lead",
    "technical lead",
    "team lead",
    "team leader",
    "lead engineer",
    "lead developer",
    "principal engineer",
    "staff engineer",
    "principal",
    "solution architect",
    "enterprise architect",

    # Product / Project
    "product manager",
    "senior product manager",
    "program manager",
    "project manager",
    "delivery manager",
    "scrum master",

    # HR / Hiring
    "hr",
    "human resources",
    "hr manager",
    "hrbp",
    "recruiter",
    "recruitment",
    "recruitment strategy",
    "talent acquisition",
    "talent acquisition manager",
    "talent",
    "hiring manager",
    "people operations",
    "people ops",
    "hr operations",
    "onboarding",
    "workforce development",

    # Business / Sales / Marketing
    "business development",
    "business development manager",
    "sales manager",
    "account manager",
    "partnership manager",
    "marketing manager",
    "growth manager",

    # Operations / Strategy
    "operations manager",
    "strategy manager",
    "consultant",
    "advisor",
]
